<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Investor;
use Doctrine\ORM\EntityRepository;

/**
 * InvestmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvestmentRepository extends EntityRepository
{
    public function getInvestmentsByInvestor(Investor $investor)
    {
        return $this->findByInvestor($investor->getId());
    }
}
